/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as NewRouteImport } from './routes/new'
import { Route as ASlugRouteImport } from './routes/a.$slug'
import { Route as ApiArtifactsRouteImport } from './routes/api/artifacts'
import { Route as ApiCollectionsRouteImport } from './routes/api/collections'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ASlugEditRouteImport } from './routes/a.$slug.edit'
import { Route as ApiArtifactsIdRouteImport } from './routes/api/artifacts.$id'
import { Route as ApiCollectionsIdRouteImport } from './routes/api/collections.$id'
import { Route as ApiArtifactsIdHtmlRouteImport } from './routes/api/artifacts.$id.html'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugRoute = ASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsRoute = ApiArtifactsRouteImport.update({
  id: '/api/artifacts',
  path: '/api/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectionsRoute = ApiCollectionsRouteImport.update({
  id: '/api/collections',
  path: '/api/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugEditRoute = ASlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ASlugRoute,
} as any)
const ApiArtifactsIdRoute = ApiArtifactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiArtifactsRoute,
} as any)
const ApiCollectionsIdRoute = ApiCollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCollectionsRoute,
} as any)
const ApiArtifactsIdHtmlRoute = ApiArtifactsIdHtmlRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => ApiArtifactsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/new': typeof NewRoute
  '/a/$slug': typeof ASlugRouteWithChildren
  '/api/artifacts': typeof ApiArtifactsRouteWithChildren
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/c/$slug': typeof CSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/a/$slug/edit': typeof ASlugEditRoute
  '/api/artifacts/$id': typeof ApiArtifactsIdRouteWithChildren
  '/api/collections/$id': typeof ApiCollectionsIdRoute
  '/api/artifacts/$id/html': typeof ApiArtifactsIdHtmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/new': typeof NewRoute
  '/a/$slug': typeof ASlugRouteWithChildren
  '/api/artifacts': typeof ApiArtifactsRouteWithChildren
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/c/$slug': typeof CSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/a/$slug/edit': typeof ASlugEditRoute
  '/api/artifacts/$id': typeof ApiArtifactsIdRouteWithChildren
  '/api/collections/$id': typeof ApiCollectionsIdRoute
  '/api/artifacts/$id/html': typeof ApiArtifactsIdHtmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/new': typeof NewRoute
  '/a/$slug': typeof ASlugRouteWithChildren
  '/api/artifacts': typeof ApiArtifactsRouteWithChildren
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/c/$slug': typeof CSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/a/$slug/edit': typeof ASlugEditRoute
  '/api/artifacts/$id': typeof ApiArtifactsIdRouteWithChildren
  '/api/collections/$id': typeof ApiCollectionsIdRoute
  '/api/artifacts/$id/html': typeof ApiArtifactsIdHtmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/new'
    | '/a/$slug'
    | '/api/artifacts'
    | '/api/collections'
    | '/api/mcp'
    | '/c/$slug'
    | '/s/$slug'
    | '/a/$slug/edit'
    | '/api/artifacts/$id'
    | '/api/collections/$id'
    | '/api/artifacts/$id/html'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/new'
    | '/a/$slug'
    | '/api/artifacts'
    | '/api/collections'
    | '/api/mcp'
    | '/c/$slug'
    | '/s/$slug'
    | '/a/$slug/edit'
    | '/api/artifacts/$id'
    | '/api/collections/$id'
    | '/api/artifacts/$id/html'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/new'
    | '/a/$slug'
    | '/api/artifacts'
    | '/api/collections'
    | '/api/mcp'
    | '/c/$slug'
    | '/s/$slug'
    | '/a/$slug/edit'
    | '/api/artifacts/$id'
    | '/api/collections/$id'
    | '/api/artifacts/$id/html'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  NewRoute: typeof NewRoute
  ASlugRoute: typeof ASlugRouteWithChildren
  ApiArtifactsRoute: typeof ApiArtifactsRouteWithChildren
  ApiCollectionsRoute: typeof ApiCollectionsRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRoute
  CSlugRoute: typeof CSlugRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug': {
      id: '/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof ASlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts': {
      id: '/api/artifacts'
      path: '/api/artifacts'
      fullPath: '/api/artifacts'
      preLoaderRoute: typeof ApiArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections': {
      id: '/api/collections'
      path: '/api/collections'
      fullPath: '/api/collections'
      preLoaderRoute: typeof ApiCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug/edit': {
      id: '/a/$slug/edit'
      path: '/edit'
      fullPath: '/a/$slug/edit'
      preLoaderRoute: typeof ASlugEditRouteImport
      parentRoute: typeof ASlugRoute
    }
    '/api/artifacts/$id': {
      id: '/api/artifacts/$id'
      path: '/$id'
      fullPath: '/api/artifacts/$id'
      preLoaderRoute: typeof ApiArtifactsIdRouteImport
      parentRoute: typeof ApiArtifactsRoute
    }
    '/api/collections/$id': {
      id: '/api/collections/$id'
      path: '/$id'
      fullPath: '/api/collections/$id'
      preLoaderRoute: typeof ApiCollectionsIdRouteImport
      parentRoute: typeof ApiCollectionsRoute
    }
    '/api/artifacts/$id/html': {
      id: '/api/artifacts/$id/html'
      path: '/html'
      fullPath: '/api/artifacts/$id/html'
      preLoaderRoute: typeof ApiArtifactsIdHtmlRouteImport
      parentRoute: typeof ApiArtifactsIdRoute
    }
  }
}

interface ASlugRouteChildren {
  ASlugEditRoute: typeof ASlugEditRoute
}

const ASlugRouteChildren: ASlugRouteChildren = {
  ASlugEditRoute: ASlugEditRoute,
}

const ASlugRouteWithChildren = ASlugRoute._addFileChildren(ASlugRouteChildren)

interface ApiArtifactsIdRouteChildren {
  ApiArtifactsIdHtmlRoute: typeof ApiArtifactsIdHtmlRoute
}

const ApiArtifactsIdRouteChildren: ApiArtifactsIdRouteChildren = {
  ApiArtifactsIdHtmlRoute: ApiArtifactsIdHtmlRoute,
}

const ApiArtifactsIdRouteWithChildren = ApiArtifactsIdRoute._addFileChildren(
  ApiArtifactsIdRouteChildren,
)

interface ApiArtifactsRouteChildren {
  ApiArtifactsIdRoute: typeof ApiArtifactsIdRouteWithChildren
}

const ApiArtifactsRouteChildren: ApiArtifactsRouteChildren = {
  ApiArtifactsIdRoute: ApiArtifactsIdRouteWithChildren,
}

const ApiArtifactsRouteWithChildren = ApiArtifactsRoute._addFileChildren(
  ApiArtifactsRouteChildren,
)

interface ApiCollectionsRouteChildren {
  ApiCollectionsIdRoute: typeof ApiCollectionsIdRoute
}

const ApiCollectionsRouteChildren: ApiCollectionsRouteChildren = {
  ApiCollectionsIdRoute: ApiCollectionsIdRoute,
}

const ApiCollectionsRouteWithChildren = ApiCollectionsRoute._addFileChildren(
  ApiCollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  NewRoute: NewRoute,
  ASlugRoute: ASlugRouteWithChildren,
  ApiArtifactsRoute: ApiArtifactsRouteWithChildren,
  ApiCollectionsRoute: ApiCollectionsRouteWithChildren,
  ApiMcpRoute: ApiMcpRoute,
  CSlugRoute: CSlugRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
